version: "3.9"

services:
  vue-app:
    container_name: vue-inventario
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"     
      - "80:80"        
    volumes:
      - ./certs:/etc/nginx/certs
    restart: unless-stopped
